### ISSUE TITLE
Doc link should point on repository at last release tag instead of current snapshot

### ISSUE THREAD

**Issue by KvanTTT** [antlr/website-antlr4#15]
I mean the following link
https://github.com/antlr/antlr4/blob/4.6/doc/index.md
should be used instead of
https://github.com/antlr/antlr4/blob/master/doc/index.md

**Comment by parrt** [comment]
good point.

**Comment by KvanTTT** [comment]
Not only this link, but other too.

**Comment by parrt** [comment]
i think i got all doc links
