### ISSUE TITLE
Add Visual Code ANTLR4 plugin to ANTLR Development Tools

### ISSUE THREAD

**Issue by KvanTTT** [antlr/website-antlr4#18]
See [ANTLR4 grammar syntax support](https://marketplace.visualstudio.com/items?itemName=mike-lischke.vscode-antlr4) plugin.

**Comment by parrt** [comment]
Done. added. @mike-lischke

**Comment by KvanTTT** [comment]
This is a Visual Code plugin, not Visual Studio.

**Comment by parrt** [comment]
ah. fixed.

**Comment by mike-lischke** [comment]
**Visual Studio Code** actually :-D

**Comment by parrt** [comment]
yeah, saw that and repushed.
